print(1 + 2.0987)
print("- - - - - - - - - - - - - - -")
print(3 * 4 + 5)
print("- - - - - - - - - - - - - - -")
print(3 * (4 + 5))
print("- - - - - - - - - - - - - - -")
print(10 % 3)
print("- - - - - - - - - - - - - - -")
my_number = 5
print(10 * my_number)
print("- - - - - - - - - - - - - - -")
my_number = 5
print(str(my_number))
print("- - - - - - - - - - - - - - -")
my_number = 5
print(str(my_number) + " is my favourite number")
print("- - - - - - - - - - - - - - -")
print("absolute value")
my_number = -5.25
print(abs(my_number))
print("- - - - - - - - - - - - - - -")
print("power of ie. 2^3")
print(pow(2, 10))
print("- - - - - - - - - - - - - - -")
print("higher number")
print(max(2, 10))
print("- - - - - - - - - - - - - - -")
print("smaller number")
print(max(2, 10))
print("- - - - - - - - - - - - - - -")
print("rounded number")
print(round(3.124327463278))
print("- - - - - - - - - - - - - - -")
